apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: dev
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_DATABASE: wanderlustwebdb
  DB_HOST: mongo-headless
  DB_USER: root
  DB_DATABASE: wanderlustwebdb
