apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: dev
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_DATABASE: wanderlustwebdb
  dbHost: mongo-headless
  dbUser: root
  dbName: wanderlustwebdb
