apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: bankapp-namespace
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017  # MongoDB default port
    targetPort: 27017
  clusterIP: None  # Creates a headless service
  selector:
    app: mongodb
