apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dev
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=  # Replace 'mypassword' with your root password (Base64 encoded)
  DB_PASSWORD: YWRtaW4=
